parameters:
    hgabka_media.media_handler.remote_slide.class: 'Hgabka\MediaBundle\Helper\RemoteSlide\RemoteSlideHandler'
    hgabka_media.media_handler.remote_video.class: 'Hgabka\MediaBundle\Helper\RemoteVideo\RemoteVideoHandler'
    hgabka_media.media_handler.remote_audio.class: 'Hgabka\MediaBundle\Helper\RemoteAudio\RemoteAudioHandler'
    hgabka_media.media_handler.image.class: 'Hgabka\MediaBundle\Helper\Image\ImageHandler'
    hgabka_media.media_handler.file.class: 'Hgabka\MediaBundle\Helper\File\FileHandler'
    aviary_api_key: null
    hgabka_media.media_path: '/uploads/media/'
    hgabka_media.protected_media_path: 'data/media/'

services:
    hgabka_media.media_handlers.remote_slide:
        public: true
        class: '%hgabka_media.media_handler.remote_slide.class%'
        arguments: [1]
        calls:
            - [ setHgabkaUtils, [ '@hgabka_utils.hgabka_utils' ] ]
        tags:
            -  { name: 'hgabka_media.media_handler' }

    hgabka_media.media_handlers.remote_video:
        public: true
        class: '%hgabka_media.media_handler.remote_video.class%'
        arguments: [1, '%hgabka_media.remote_video%']
        calls:
            - [ setHgabkaUtils, [ '@hgabka_utils.hgabka_utils' ] ]
        tags:
            -  { name: 'hgabka_media.media_handler' }

    hgabka_media.media_handlers.remote_audio:
        public: true
        class: '%hgabka_media.media_handler.remote_audio.class%'
        arguments: [1, '%hgabka_media.soundcloud_api_key%']
        calls:
            - [ setHgabkaUtils, [ '@hgabka_utils.hgabka_utils' ] ]
        tags:
            -  { name: 'hgabka_media.media_handler' }

    hgabka_media.media_handlers.image:
        public: true
        class: '%hgabka_media.media_handler.image.class%'
        arguments: [1, '@mime_types', '%aviary_api_key%']
        calls:
            - [ setUrlGenerator, [ '@router' ] ]
            - [ setFileSystem, [ '@hgabka_media.filesystem' ] ]
            - [ setProtectedFileSystem, [ '@hgabka_media.filesystem_protected' ] ]
            - [ setMediaPath, [ '%hgabka_media.media_path%' ] ]
            - [ setProtectedMediaPath, [ '%hgabka_media.protected_media_path%' ] ]
            - [ setBlacklistedExtensions, [ '%hgabka_media.blacklisted_extensions%' ] ]
            - [ setHgabkaUtils, ['@hgabka_utils.hgabka_utils']]
            - [ setFolderDepth, ['%hgabka_media.folder_depth%']]
        tags:
            -  { name: 'hgabka_media.media_handler' }

    hgabka_media.media_handlers.file:
        public: true
        class: '%hgabka_media.media_handler.file.class%'
        arguments: [0, '@mime_types', '']
        calls:
            - [ setUrlGenerator, [ '@router' ] ]
            - [ setFileSystem, [ '@hgabka_media.filesystem' ] ]
            - [ setProtectedFileSystem, [ '@hgabka_media.filesystem_protected' ] ]
            - [ setMediaPath, [ '%hgabka_media.media_path%' ] ]
            - [ setProtectedMediaPath, [ '%hgabka_media.protected_media_path%' ] ]
            - [ setBlacklistedExtensions, [ '%hgabka_media.blacklisted_extensions%' ] ]
            - [ setHgabkaUtils, ['@hgabka_utils.hgabka_utils']]
            - [ setFolderDepth, ['%hgabka_media.folder_depth%']]
        tags:
            -  { name: 'hgabka_media.media_handler' }
