HgabkaMediaBundle_media:
    resource: '@HgabkaMediaBundle/Controller/MediaController.php'
    type:     attribute
    prefix:   '/media'
        
HgabkaMediaBundle_aviary:
    resource: '@HgabkaMediaBundle/Controller/AviaryController.php'
    type:     attribute
    prefix:   /
        
HgabkaMediaBundle_media_chooser:
    resource: '@HgabkaMediaBundle/Controller/ChooserController.php'
    type:     attribute
    prefix:   '/media'
        
HgabkaMediaBundle_media_folder:
    resource: '@HgabkaMediaBundle/Controller/FolderController.php'
    type:     attribute
    prefix:   '/media/folder'

HgabkaMediaBundle_icon_font:
    resource: '@HgabkaMediaBundle/Controller/IconFontController.php'
    type:     attribute
    prefix:   '/media/icon-font'
