parameters:
    hgabka_media.media_manager.class: 'Hgabka\MediaBundle\Helper\MediaManager'
    hgabka_media.folder_manager.class: 'Hgabka\MediaBundle\Helper\FolderManager'
    hgabka_media.menu.adaptor.class: 'Hgabka\MediaBundle\Helper\Menu\MediaMenuAdaptor'
    hgabka_media.listener.doctrine.class: 'Hgabka\MediaBundle\EventListener\DoctrineMediaListener'
    hgabka_media.form.type.media.class: 'Hgabka\MediaBundle\Form\Type\MediaType'
    hgabka_media.form.type.media_simple.class: 'Hgabka\MediaBundle\Form\Type\MediaSimpleType'
    hgabka_media.form.type.folder.class: 'Hgabka\MediaBundle\Form\FolderType'
    hgabka_media.form.type.iconfont.class: 'Hgabka\MediaBundle\Form\Type\IconFontType'
    hgabka_media.icon_font_manager.class: 'Hgabka\MediaBundle\Helper\IconFont\IconFontManager'
    hgabka_media.icon_font.default_loader.class: 'Hgabka\MediaBundle\Helper\IconFont\DefaultIconFontLoader'
    hgabka_media.media_creator_service.class: 'Hgabka\MediaBundle\Helper\Services\MediaCreatorService'
    hgabka_media.validator.has_guessable_extension.class: 'Hgabka\MediaBundle\Validator\Constraints\HasGuessableExtensionValidator'

services:
    hgabka_media.media_manager:
        class: '%hgabka_media.media_manager.class%'
        arguments: ['@hgabka_utils.hgabka_utils', '%kernel.project_dir%']
        calls:
            - [ setDefaultHandler, [ '@hgabka_media.media_handlers.file' ] ]
        public: true

    hgabka_media.listener.doctrine:
        class: '%hgabka_media.listener.doctrine.class%'
        arguments: ['@hgabka_media.media_manager']
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }

    form.type.media:
        class: '%hgabka_media.form.type.media.class%'
        arguments:
            - '@hgabka_media.media_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type}
        public: true

    form.type.media_simple:
        class: '%hgabka_media.form.type.media_simple.class%'
        arguments:
            - '@hgabka_media.media_manager'
            - '@doctrine.orm.entity_manager'
            - '@hgabka_utils.hgabka_utils'
        tags:
            - { name: form.type}
        public: true

    form.type.folder:
        class: '%hgabka_media.form.type.folder.class%'
        arguments:
            - '@hgabka_utils.hgabka_utils'
            - '@security.authorization_checker'
        tags:
            - { name: form.type}
        public: true

    form.type.iconfont:
        class: '%hgabka_media.form.type.iconfont.class%'
        arguments: ['@hgabka_media.icon_font_manager']
        tags:
            - { name: form.type }

    hgabka_media.icon_font_manager:
        class: '%hgabka_media.icon_font_manager.class%'
        calls:
            - [ setDefaultLoader, [ '@hgabka_media.icon_font.default_loader' ] ]

    hgabka_media.icon_font.default_loader:
        class: '%hgabka_media.icon_font.default_loader.class%'
        arguments: ['@kernel']
        tags:
            -  { name: 'hgabka_media.icon_font.loader' }

    hgabka_media.media_creator_service:
        class: '%hgabka_media.media_creator_service.class%'
        arguments: ['@service_container']

    hgabka_media.repository.folder:
        class:            Hgabka\MediaBundle\Repository\FolderRepository
        factory:          ['@doctrine.orm.entity_manager', getRepository]
        arguments:        ['HgabkaMediaBundle:Folder']

    hgabka_media.menu.adaptor:
        class: '%hgabka_media.menu.adaptor.class%'
        arguments: ['@hgabka_media.repository.folder']
        tags:
            -  { name: 'hgabka_admin.menu.adaptor' }

    hgabka_media.folder_manager:
        class: '%hgabka_media.folder_manager.class%'
        arguments: ['@hgabka_media.repository.folder']
        public: true


    Hgabka\MediaBundle\Command\RebuildFolderTreeCommand:
        autowire: true
        autoconfigure: true

    Hgabka\MediaBundle\Command\CleanDeletedMediaCommand:
        class: Hgabka\MediaBundle\Command\CleanDeletedMediaCommand
        autowire: true
        autoconfigure: true

    hgabka_media.filesystem_adapter:
        class: Gaufrette\Adapter\Local
        arguments:
            - '%kernel.project_dir%/public%hgabka_media.media_path%'
            - true

    hgabka_media.filesystem:
        class: Gaufrette\Filesystem
        arguments:
            - '@hgabka_media.filesystem_adapter'

    hgabka_media.validator.has_guessable_extension:
        class: '%hgabka_media.validator.has_guessable_extension.class%'
        tags:
            - { name: validator.constraint_validator, alias: has_guessable_extension }
        calls:
            - [setGuesser, ['@mime_types']]
  
    hgabka_media.media.twig.extension:
        class: Hgabka\MediaBundle\Twig\MediaTwigExtension
        arguments: ['@hgabka_media.media_manager', '@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    hg_media.admin.media:
        class: Hgabka\MediaBundle\Admin\MediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: hg_media.group, icon: '<i class="fa fa-image"></i>', label: hg_media.admin.label, label_catalogue: 'HgabkaMediaBundle', label_translator_strategy: 'sonata.admin.label.strategy.underscore' }
        arguments: [null, Hgabka\MediaBundle\Entity\Media, Hgabka\MediaBundle\Controller\MediaAdminController]
        calls:
          - [setManager, ["@hgabka_media.media_manager"]]

    Hgabka\MediaBundle\DataFixtures\ORM\FolderFixtures:
        tags:
            - { name: doctrine.fixture.orm }

    Hgabka\MediaBundle\Admin\Menu\AdminMenuListener:
        autowire: true
        arguments: ['@hg_media.admin.media', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }

    Hgabka\MediaBundle\Helper\FolderManager: '@hgabka_media.folder_manager'
    Hgabka\MediaBundle\Helper\MediaManager: '@hgabka_media.media_manager'
    Hgabka\MediaBundle\Admin\MediaAdmin: '@hg_media.admin.media'
    Hgabka\MediaBundle\Helper\Services\MediaCreatorService: '@hgabka_media.media_creator_service'

    Hgabka\MediaBundle\Controller\ChooserController:
        autoconfigure: true
        autowire: true
        calls:
            - [setTemplateRegistry, ['sonata.admin.global_template_registry']]
        tags: ['controller.service_arguments']

    Hgabka\MediaBundle\Controller\FolderController:
        autoconfigure: true
        autowire: true
        calls:
            - [setTemplateRegistry, ['sonata.admin.global_template_registry']]
        tags: ['controller.service_arguments']

    Hgabka\MediaBundle\Controller\MediaController:
        autoconfigure: true
        autowire: true
        calls:
            - [setTemplateRegistry, ['sonata.admin.global_template_registry']]
        tags: ['controller.service_arguments']

    Hgabka\MediaBundle\Controller\MediaAdminController:
        autoconfigure: true
        autowire: true
        calls:
            - [setTemplateRegistry, ['sonata.admin.global_template_registry']]
        tags: ['controller.service_arguments']

    Hgabka\MediaBundle\Controller\AviaryController:
        autoconfigure: true
        autowire: true
        calls:
            - [setTemplateRegistry, ['sonata.admin.global_template_registry']]
        tags: ['controller.service_arguments']
        
    Hgabka\MediaBundle\Helper\SvgMimeTypeGuesser:
        autowire: true
        autoconfigure: true
    
